In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sales =pd.read_csv("sales_cleaned.csv")
products = pd.read_csv("products_cleaned.csv")
customers = pd.read_csv("customers_cleaned.csv")

In [3]:

#drop column create_date
customers.drop(columns=["create_date"],inplace=True)

In [4]:
customers.head()

,customer_key,customer_id,customer_number,first_name,last_name,country,marital_status,gender,age
0,1,11000,AW00011000,Jon,Yang,Australia,Married,Male,54.0
1,2,11001,AW00011001,Eugene,Huang,Australia,Single,Male,49.0
2,3,11002,AW00011002,Ruben,Torres,Australia,Married,Male,55.0
3,4,11003,AW00011003,Christy,Zhu,Australia,Single,Female,52.0
4,5,11004,AW00011004,Elizabeth,Johnson,Australia,Single,Female,46.0

In [5]:
customers.insert(customers.columns.get_loc("customer_number") + 1,"full_name",customers["first_name"] + " " + customers["last_name"])

In [6]:
customers.head()

,customer_key,customer_id,customer_number,full_name,first_name,last_name,country,marital_status,gender,age
0,1,11000,AW00011000,Jon Yang,Jon,Yang,Australia,Married,Male,54.0
1,2,11001,AW00011001,Eugene Huang,Eugene,Huang,Australia,Single,Male,49.0
2,3,11002,AW00011002,Ruben Torres,Ruben,Torres,Australia,Married,Male,55.0
3,4,11003,AW00011003,Christy Zhu,Christy,Zhu,Australia,Single,Female,52.0
4,5,11004,AW00011004,Elizabeth Johnson,Elizabeth,Johnson,Australia,Single,Female,46.0

In [7]:
#drop the first_name and last_name
customers.drop(columns=["first_name","last_name"],inplace=True)

In [8]:
customers.head()

,customer_key,customer_id,customer_number,full_name,country,marital_status,gender,age
0,1,11000,AW00011000,Jon Yang,Australia,Married,Male,54.0
1,2,11001,AW00011001,Eugene Huang,Australia,Single,Male,49.0
2,3,11002,AW00011002,Ruben Torres,Australia,Married,Male,55.0
3,4,11003,AW00011003,Christy Zhu,Australia,Single,Female,52.0
4,5,11004,AW00011004,Elizabeth Johnson,Australia,Single,Female,46.0

In [9]:
sales.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO43697,20,10769,2010-12-29,2011-01-05,2011-01-10,3578,1,3578
1,SO43698,9,17390,2010-12-29,2011-01-05,2011-01-10,3400,1,3400
2,SO43699,9,14864,2010-12-29,2011-01-05,2011-01-10,3400,1,3400
3,SO43700,41,3502,2010-12-29,2011-01-05,2011-01-10,699,1,699
4,SO43701,9,4,2010-12-29,2011-01-05,2011-01-10,3400,1,3400

"The original dataset contained sales data from 2010–2014.
For realistic business analysis and forecasting demonstration, the dates were shifted to 2021–2025."

In [10]:
sales["order_date"]= pd.to_datetime(sales["order_date"])

In [11]:
date_cols = ["order_date", "shipping_date", "due_date"]
for col in date_cols:
    sales[col] = pd.to_datetime(sales[col]) + pd.DateOffset(years=10)

In [12]:
sales.head()

,order_number,product_key,customer_key,order_date,shipping_date,due_date,sales_amount,quantity,price
0,SO43697,20,10769,2020-12-29,2021-01-05,2021-01-10,3578,1,3578
1,SO43698,9,17390,2020-12-29,2021-01-05,2021-01-10,3400,1,3400
2,SO43699,9,14864,2020-12-29,2021-01-05,2021-01-10,3400,1,3400
3,SO43700,41,3502,2020-12-29,2021-01-05,2021-01-10,699,1,699
4,SO43701,9,4,2020-12-29,2021-01-05,2021-01-10,3400,1,3400

Lets check the quality of the data frame after we changed.

In [13]:
sales[
    (sales["shipping_date"] < sales["order_date"]) |
    (sales["due_date"] < sales["shipping_date"])
]

Empty DataFrame
Columns: [order_number, product_key, customer_key, order_date, shipping_date, due_date, sales_amount, quantity, price]
Index: []

In [14]:
sales.isnull().sum()

order_number     0
product_key      0
customer_key     0
order_date       0
shipping_date    0
due_date         0
sales_amount     0
quantity         0
price            0
dtype: int64

In [18]:
products.head()

,product_key,product_id,product_number,product_name,category_id,category_name,sub_category,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,869,Road,2003-07-01
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,869,Road,2003-07-01
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2011-07-01

In [21]:
products["start_date"] = pd.to_datetime(products["start_date"])
products["start_date"].dt.year.unique()

array([2003, 2011, 2012, 2013], dtype=int32)

"The original dataset contained sales data from [2003, 2011, 2012, 2013].
For realistic business analysis and forecasting demonstration, the dates were shifted to [200=13, 2021, 2022, 2023]."

In [22]:
products["start_date"] = pd.to_datetime(products["start_date"]) + pd.DateOffset(years=10)

In [23]:
products.head()

,product_key,product_id,product_number,product_name,category_id,category_name,sub_category,maintenance,cost,product_line,start_date
0,1,210,FR-R92B-58,HL Road Frame - Black- 58,CO_RF,Components,Road Frames,Yes,869,Road,2013-07-01
1,2,211,FR-R92R-58,HL Road Frame - Red- 58,CO_RF,Components,Road Frames,Yes,869,Road,2013-07-01
2,3,348,BK-M82B-38,Mountain-100 Black- 38,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2021-07-01
3,4,349,BK-M82B-42,Mountain-100 Black- 42,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2021-07-01
4,5,350,BK-M82B-44,Mountain-100 Black- 44,BI_MB,Bikes,Mountain Bikes,Yes,1898,Mountain,2021-07-01

In [24]:
customers.to_csv("customers.csv", index=False)
products.to_csv("products.csv", index=False)
sales.to_csv("sales.csv", index=False)

In [25]:
from google.colab import files
files.download("customers.csv")
files.download("products.csv")
files.download("sales.csv")